_composite_object_fixture_api:
    type:     annotation
    resource: "@GlavwebCompositeObjectBundle/Controller/Api/FixtureApiController.php"

_composite_object_object_api:
    type:     annotation
    resource: "@GlavwebCompositeObjectBundle/Controller/Api/ObjectApiController.php"

_composite_object_captcha_api:
    type:     annotation
    resource: "@GlavwebCompositeObjectBundle/Controller/Api/CaptchaApiController.php"

